use Payments;
CREATE TABLE Payments(
    id INT AUTO_INCREMENT PRIMARY KEY,
    active VARCHAR(200) NOT NULL,
    hours VARCHAR(200) NOT NULL,
    plan VARCHAR(200) NOT NULL,
    user VARCHAR(200) NOT NULL,
    pay VARCHAR(200) NOT NULL,
    startDate DATE NOT NULL,
    finishDate DATE NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);