use Plans;
CREATE TABLE Plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    price DOUBLE NOT NULL,
    description VARCHAR(200) NOT NULL,
    duration INTEGER NOT NULL,
    user VARCHAR(200) NOT NULL,
    features VARCHAR(200) NOT NULL,
    restrictions VARCHAR(200) NOT NULL,
    status BOOLEAN NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);