use Courses;
CREATE TABLE Courses(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    institution VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
    hours VARCHAR(200) NOT NULL,
    user VARCHAR(200) NOT NULL,
    startDate DATE NOT NULL,
    finishDate DATE NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);